### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dchinmay2** [nvim-telescope/telescope-packer.nvim#1]
I get
`[telescope] [WARN  12:16:38] ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:527: Failed with msg:  Vim:E730: using List as a String`

when I `:lua require('telescope').extensions.packer.plugins(opts)`

(This is how I'm supposed to use this right?)

**Comment by Conni2461** [comment]
No you did everything correct. @sunjon just uses an interface that was not yet merged. Will be fixed soon.

Using https://github.com/nvim-telescope/telescope.nvim/pull/304 for `telescope.nvim` should fix your issue.

**Comment by p00f** [comment]
can you ping me here when it gets merged? i dont wanna subscribe to pr reviews to be notified of merge 😅
