### ISSUE TITLE
Selecting a plugin should open its doc

### ISSUE THREAD

**Issue by dchinmay2** [nvim-telescope/telescope-packer.nvim#4]
Selecting a plugin should look for files in `doc/` and if there are multiple files choose the one with the shortest name because it is likely to be the main one. (Or use telescope to select from multiple docs :eyes: )

**Comment by dchinmay2** [comment]
although, you can already view doc using Telescope help_tags

**Comment by Conni2461** [comment]
I think this should open the readme now https://github.com/nvim-telescope/telescope-packer.nvim/commit/b9ffb7fc57973d4a49deb5599b845bc81f9de213

I dont use packer sorry, so i cant test it and i havent seen sunjon for quite some time so i merged it :laughing: 

I know it doesnt really do exactly what you want but its something :laughing:

**Comment by dchinmay2** [comment]
Thanks!
