### ISSUE TITLE
Plugin causes Packer to try to remove all plugins on sync,update etc.

### ISSUE THREAD

**Issue by akinsho** [nvim-telescope/telescope-packer.nvim#8]
Hi @sunjon,

just an FYI we've seen a few issues trickle in over time of users having packer try to remove all their plugins on packer  management commands like `sync`, `update` etc. These have historically been narrowed down to this plugin. 

The most recent example that reminded me to actually open this issue is https://github.com/wbthomason/packer.nvim/issues/625, https://github.com/wbthomason/packer.nvim/issues/546#issuecomment-912247471 (there are a few others, but I forget which exactly).

I'm not sure if this plugin is still maintained, if it isn't, I think add a warning about this issue would really help out in packer land and if it is, it seems to need to be updated to keep up with packer changes.

Thanks 🙏🏿

**Comment by Conni2461** [comment]
https://github.com/nvim-telescope/telescope-packer.nvim/commit/09fa9bb9ee83fa230db1087ce47f9450fc4dba15 should have just fixed it.

Dont use packer so i cant test :laughing:

**Comment by akinsho** [comment]
Thanks for having a look 👍🏿 will try it out later to check. Looking through the code a little the plugin is dependent on packer internals to list the installed plugins which could change in the future whereas there is now an exposed way to get the list of managed packer plugins i.e. `_G.packer_plugins` 🤷🏿‍♂️ more of an FYI, but I don't think this is being actively developed maybe.

**Comment by akinsho** [comment]
Just checked and seems to have worked as far as I can tell 👍🏿 thanks 🚀

**Comment by Conni2461** [comment]
:+1: 

Yeah this repo isnt maintain anymore. I am the wrong person to do that but i can merge any PR that is opened :laughing:
